/* eslint-disable no-unused-expressions */
/* eslint-disable no-unused-vars */
/* eslint-disable array-callback-return */
/* eslint-disable jsx-a11y/img-redundant-alt */
import React, { useState } from 'react'
import img1 from './2131.jpg'
import img2 from './2133.jpg'
import img3 from './2135.jpg'
import img4 from './2139.jpg'
import img5 from './2159.jpg'
import img6 from './2164.jpg'
import img7 from './2167.jpg'
import img8 from './2169.jpg'
import img9 from './2175.jpg'
import img10 from './2370.jpg'
import img11 from './2372.jpg'
import img12 from './2374.jpg'
import img13 from './2376.jpg'
import img14 from './2379.jpg'

export default function BlurryImg() {

    const [useDatas, setData] = useState(20)
    let data = {
    cardData:[
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:1,
            imgSrc:img1
        },
        
        {
            id:2,
            imgSrc:img2
        },
        {
            id:3,
            imgSrc:img3
        },
        {
            id:4,
            imgSrc:img4
        },
        {
            id:5,
            imgSrc:img5
        },
        {
            id:6,
            imgSrc:img6
        },
        {
            id:7,
            imgSrc:img7
        },
        {
            id:8,
            imgSrc:img8
        },
        {
            id:9,
            imgSrc:img9
        },
        {
            id:10,
            imgSrc:img10
        },
        {
            id:11,
            imgSrc:img11
        },
        {
            id:12,
            imgSrc:img12
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
        {
            id:13,
            imgSrc:img13
        },
        {
            id:14,
            imgSrc:img14
        },
    ]
    }
 



   const leal_more = ()=> {
    setData(useDatas+10)
  
   }

const imageHeight = 200
const imagewidth = 150



let mineData = data.cardData.slice(0 ,useDatas )

  return (
<centar>
<div className='allP'>{

                
     mineData.map((item , index)=>(
       
            
   
            <div className='show' key={index.id}>
                    <img
                        className='BlurryImg'
                        src={item.imgSrc}
                        alt='image'                        
                        loading='lazy'
                        id={item.id}
                        height={imageHeight}
                        width={imagewidth}

                    >
                    </img>
                    <p>{index+1}</p>

                   
                </div>
            
             
            ))
        
        
        }
        </div>
        <button className='seeMoreBtn' onClick={ ()=> leal_more()}> See More...</button>
</centar>
  )
}
